### ISSUE TITLE
Withhold Georeference query edit

### ISSUE THREAD

**Issue by laurarussell** [VertNet/toolkit#21]
When using the withhold georeference query along with legacy coordinates query, the decimal latitude and longitude fields are still populated as the withhold georeference query removes the georeference fields from SimpleDwC-verbatim.  The legacy coordinates query is pulling verbatim coordinates from specimens table to populate decimallatitude and decimallongitude and this happens sequentially after the withhold query runs.  So either the withhold query needs to be run after the legacy coordinates queries run or the legacy coordinates query should be based on SimpleDwC-verbatim (which is what we did to resolve the issue in the MMNS migrator).

**Comment by tucotuco** [comment]
The Legacy Coordinates Query can not be based on the SimpleDwC-verbatim table, because that may not be populated with all of the necessary fields from the source, given that only one-to-one mappings to DwC can go in at that stage. 

The geography must be withheld before the VerbatimLocality string is constructed so that geography does not creep in there either. 

Rather than move just the "Withhold georeference fields" query to after the Legacy processing and thus apart from the other withholding queries, it is better (and the migrator will run faster) if the "Legacy Coordinates processing queries are simply not enabled when georeferences are supposed to be withheld.

Hence, no change will be made to the migrator for this one.
